### ISSUE TITLE
Duplicate Google Knowledge Panel Message

### ISSUE THREAD

**Issue by zgrimz** [zgrimz/TransparentFeeDMV#2]
Sometimes, the Google Knowledge Panel message appears more than once on the search results page after scrolling around on the page or navigating to another webpage and returning to the search results.

Reproduction Steps:
- Conduct [a search on Google for one of the restaurants that will pull up a Google Knowledge Panel](https://www.google.com/search?q=all+purpose+dc+riverfront&oq=all+pur&aqs=chrome.0.69i59j0i433i512j69i59j46i175i199i512j0i512j46i175i199i512j69i60l2.1868j0j7&sourceid=chrome&ie=UTF-8#ip=1).
- Observe the Google Knowledge Panel message on the search results page.
- Scroll around on the page or navigate to another webpage.
- Return to the search results.
- Note that the Google Knowledge Panel message may appear more than once.

![Image](https://user-images.githubusercontent.com/14850533/236642962-7e37a8ec-6cd8-40ef-a62f-54b42ff7c30e.png)

**Comment by magwitch324** [comment]
Fixed in https://github.com/zgrimz/TransparentFeeDMV/commit/12350e8b94a360b790d344ab1c3edbf756c2122e
